name: Release master version

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:        
    - name: Checkout repo
      uses: actions/checkout@v3
    
    - name: Install required packages
      run: sudo apt-get install zip

    - name: Zip the integration folder
      run: zip sermatec_inverter.zip custom_components/sermatec_inverter

    - name: Publish the release 
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          ${{github.workspace}}/sermatec_inverter.zip
